stages:
  - build
  - test
  - deploy
  
variables:
  PROJECT_NAME: cfa

build:
  image: node:lts-alpine
  stage: build
  tags:
    # - dind
    - runner-java
  before_script:
    - npm cache clean --force
    - echo "before install"
    - ls -la
    - npm install
    - echo "after install"
    - ls -la
  script:
    - echo "before build"
    - ls -la
    - npm run build
    - echo "after build"
    - ls -la

  artifacts:
    name: $PROJECT_NAME
    expire_in: 1 hour
    paths:
      - cfa

archive:
  image: lgatica/openssh-client
  stage: deploy
  tags:
    # - dind
    - runner-java
  script:
    - echo "$ARCHIVE_PKEY" > archive_pkey
    - chmod 400 archive_pkey
    - chmod 700 .
    - echo "put -rp $ARCHIVE_PATH/$ARCHIVE_NAME $ARCHIVE_NAME" > archive_batch
    - >
      sftp
      -i archive_pkey
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -b archive_batch
      $ARCHIVE_USER@$ARCHIVE_HOST
  only:
    - dev
