image: node:lts-alpine

stages:
  - init
  

npm_cache:
  stage: init
  tags:
    - runner-java
  script:
    - npm install
  cache:
    key: node_modules
    paths:
      - node_modules/
    policy: push
  only:
    - dev-kanha